authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from . import views


app_name = 'authors'


author_api_router = SimpleRouter()
author_api_router.register('api', views.AuthorViewSet, basename='author-api')



urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="register_create"),

    path('login/', views.login_view, name="login"),
    path('login/create/', views.login_create, name="login_create"),
    
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/recipe/new/', views.DashboardRecipe.as_view(), name="dashboard_recipe_new"),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(), name="dashboard_recipe_delete"),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipe.as_view(), name="dashboard_recipe_edit"),
    path('profile/<int:id>/', views.ProfileView.as_view(), name="profile"),
]   

urlpatterns += author_api_router.urls

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



recipes/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView, TokenVerifyView)



app_name = 'recipes'

recipe_api_v2_router = SimpleRouter()
recipe_api_v2_router.register('recipes/api/v2', views.RecipeAPIv2ViewSet, basename='recipe-api')

urlpatterns = [
    path('', views.RecipeListViewHome.as_view(), name="home"),
    path('recipes/search/', views.RecipeListViewSearch.as_view(), name="search"),
    path('recipes/tags/<slug:slug>/', views.RecipeListViewTag.as_view(), name="tag"),
    path('recipes/category/<int:category_id>/', views.RecipeListViewCategory.as_view(), name="category"),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name="recipe"),

    path('recipes/api/v1/', views.RecipeListViewHomeApi.as_view(), name="recipe_api_v1"),
    path('recipes/api/v1/<int:pk>/', views.RecipeDetailAPI.as_view(), name="recipe_api_v1_detail"),
    path('recipes/api/v2/tag/<int:pk>/', views.tag_api_detail, name="recipe_api_v2_tag"),

    path('recipes/api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('recipes/api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('recipes/api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    path('', include(recipe_api_v2_router.urls))
]



authors/forms/recipe_form.py
from collections import defaultdict
from django import forms
from recipes.models import Recipe
from utils.django_forms import add_attr
from django.core.exceptions import ValidationError
from authors.validators import AuthorRecipeValidator

class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)
        self._my_errors

        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        add_attr(self.fields.get('cover'), 'class', 'span-2')

    class Meta:
        model = Recipe
        fields = 'title', 'description', 'preparation_time', \
              'preparation_time_unit', 'servings', 'servings_unit', \
              'preparation_steps',  'cover'
        widgets = {'cover': forms.FileInput(attrs={ 'class': 'span-2'}), 'servings_unit': forms.Select(
            choices=(
                    ('Poeções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoa', 'Pessoa'),
                    ),
                ),
                'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                    ('Dia', 'Dia'),
                    ),
                ),
            }
              
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        AuthorRecipeValidator(self.cleaned_data, ErrorClass=ValidationError)
        return super_clean
   

recipes/views/api.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from tag.models import Tag
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet
from django.shortcuts import get_object_or_404
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework import status


from ..models import Recipe
from ..serialirzers import RecipeSerializer, TagSerializer
from ..permissions import IsOwner

class RecipeAPIv2Pagination(PageNumberPagination):
    page_size = 2


class RecipeAPIv2ViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = RecipeAPIv2Pagination
    permission_classes = [IsAuthenticatedOrReadOnly]
    http_method_names = ['get', 'options', 'head', 'patch', 'post', 'delete']
    
    
    def get_queryset(self):
        qs = super().get_queryset()

        category_id = self.request.query_params.get('category_id', '')

        if category_id != '' and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)

        return qs


    def get_object(self):
        pk = self.kwargs.get('pk', '')

        obj = get_object_or_404(self.get_queryset(), pk=pk)

        self.check_object_permissions(self.request, obj)

        return obj


    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner(),]
            
        return super().get_permissions()


    def create(self, request, *args, **kwargs):
            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            serializer.save(author=request.user)
            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


    def partial_update(self, request, *args, **kwargs):
            recipe = self.get_object()
            serializer = RecipeSerializer(
                instance=recipe,
                data=request.data,
                many=False,
                context={'request': request},
                partial=True,
            )
            serializer.is_valid(raise_exception=True)
            serializer.save()

            return Response(serializer.data,)
            


@api_view()
def tag_api_detail(request, pk):
    tag = get_object_or_404(Tag.objects.all(), pk=pk)
    serializer = TagSerializer(instance=tag, many=False, context={'request': request})
    return Response(serializer.data)

recipes/views/list_views_recipe.py
import os
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import ListView, DetailView
from recipes.models import Recipe
from utils.pagination import make_pagination
from django.db.models import Q
from django.http import Http404
from django.http import JsonResponse
from django.forms.models import model_to_dict
from tag.models import Tag
from django.utils import translation
from django.utils.translation import gettext as _

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        qs = qs.select_related('author', 'category', 'author__profile')
        qs = qs.prefetch_related('tags')
        return qs
        

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(self.request, ctx.get('recipes'), PER_PAGE)
        html_language = translation.get_language()

        ctx.update({'recipes': page_obj, 'pagination_range': pagination_range, 'html_language' : html_language})
        return ctx

    

class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'



class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data()['recipes']
        recipes_list = recipes.object_list.values()


        return JsonResponse(list(recipes_list), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        ctx.update({'title': f'{ctx.get("recipes")[0].category.name}- 'f'{category_translation} |'})
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(category__id=self.kwargs.get('category_id'))

        if not qs:
            raise Http404()

        return qs
        



class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(Q(Q(title__icontains=search_term) | Q(description__icontains=search_term),), is_published=True).order_by('-id')
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        ctx.update({'page_title': f'Search for "{search_term}"', 'search_term': search_term, 'additional_url_query': f'&q={search_term}',})
        return ctx
    

class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs
            
        

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({'is_detail_page': True})
        return ctx
    


class RecipeDetailAPI(RecipeDetail):
    def render_to_response(self, context, **response_Kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        recipe_dict['created_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.updated_at)

        if recipe_dict.get('cover'):
            recipe_dict['cover'] = self.request.build_absolute_uri() + recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''

        del recipe_dict['is_published']
        del recipe_dict['preparation_steps_is_html']

        return JsonResponse(recipe_dict, safe=False)
    

class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({'page_title': page_title})
        return ctx
    

recipes/views/site.py
import os
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import ListView, DetailView
from recipes.models import Recipe
from utils.pagination import make_pagination
from django.db.models import Q
from django.http import Http404
from django.http import JsonResponse
from django.forms.models import model_to_dict
from tag.models import Tag
from django.utils import translation
from django.utils.translation import gettext as _

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        qs = qs.select_related('author', 'category', 'author__profile')
        qs = qs.prefetch_related('tags')
        return qs
        

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(self.request, ctx.get('recipes'), PER_PAGE)
        html_language = translation.get_language()

        ctx.update({'recipes': page_obj, 'pagination_range': pagination_range, 'html_language' : html_language})
        return ctx

    

class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'



class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data()['recipes']
        recipes_list = recipes.object_list.values()


        return JsonResponse(list(recipes_list), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        ctx.update({'title': f'{ctx.get("recipes")[0].category.name}- 'f'{category_translation} |'})
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(category__id=self.kwargs.get('category_id'))

        if not qs:
            raise Http404()

        return qs
        



class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(Q(Q(title__icontains=search_term) | Q(description__icontains=search_term),), is_published=True).order_by('-id')
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        ctx.update({'page_title': f'Search for "{search_term}"', 'search_term': search_term, 'additional_url_query': f'&q={search_term}',})
        return ctx
    

class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs
            
        

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({'is_detail_page': True})
        return ctx
    


class RecipeDetailAPI(RecipeDetail):
    def render_to_response(self, context, **response_Kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        recipe_dict['created_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.updated_at)

        if recipe_dict.get('cover'):
            recipe_dict['cover'] = self.request.build_absolute_uri() + recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''

        del recipe_dict['is_published']
        del recipe_dict['preparation_steps_is_html']

        return JsonResponse(recipe_dict, safe=False)
    

class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({'page_title': page_title})
        return ctx
    

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'recipe/css/css.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css" integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css" integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css" integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

recipes/templates/recipes/partials/recipe.html
{% load i18n %}

<div class="recipe recipe-list-item">
    {% if recipe.cover %}
    <div class="recipe-list-cover">
        <a href="{{ recipe.get_absolute_url }}">
            <img src="{{ recipe.cover.url }}" alt="img">
        </a>
    </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{{ recipe.get_absolute_url }}">
                {{recipe.title}}
            </a>
        </h2>
    </div>

    <div class="recipe-author">

        {% if recipe.author is not None %}
            <span class="recipe-author-item">

            {% if recipe.author.profile %}
                <a href="{% url 'authors:profile' recipe.author.profile.id %}">
            {% endif %}

            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}

            {% if recipe.author.profile %}
                </a>
            {% endif %}

            </span>
        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y H:i:s" }} ás {{ recipe.created_at|date:"H:i" }}
        </span>
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> {% translate "Preparation" %}</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"> <i class="fas fa-pizza-slice"></i> {% translate "Servings" %} </h3> 
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span> {% translate 'read more' %}... </span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
        {% endif %}
            </div>
    {% endif %}

    {% if recipe.tags.all %}
            <p>
                Tags:
                    {% for tag in recipe.tags.all %}
                        <a href="{% url 'recipes:tag' tag.slug %}">{{ tag.name }}</a>, 
                    {% endfor %}
            </p>
    {% endif %}

</div>